# Generated by Django 3.2.4 on 2021-10-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetups',
            new_name='Meetup',
        ),
    ]
